
project:
  api:
    # domain which will be appended in the email links URLs, without / at the end
    # final URL example: http://localhost:8080/api/registration/activateAccount
    domainUrl: "https://user-api-oldbot.herokuapp.com"

server:
  port: 8080


spring:
  # On "development" profile, use "update" to create the tables
  jpa:hibernate:ddl-auto: update

  # Mail service configuration
  mail:
    sender_email: "support@oldbot.com.br"
    sender_name: "No Reply OldBot"
    host: smtp.titan.email
    # recommended to use environment variables for sensitive information
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:enable: true


  rabbitmq:
    addresses: ${RABBITMQ_URL}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    queue: "EMAIL"
    exchange: "amq.direct"