
project:
  api:
    # domain which will be appended in the email links URLs, without / at the end
    # final URL example: http://localhost:8080/api/registration/activateAccount
    domainUrl: "https://user-api-oldbot.herokuapp.com"

server:
  port: 8080


spring:
  # On "development" profile, use "update" to create the tables
  jpa:hibernate:ddl-auto: update

  # Mail service configuration
  mail:
    # Use your environment variables
    # Example: "No Reply <YOUR_SERVICE>"
    sender_name: ${SMTP_SENDER_NAME}
    # Example: "support@yourservice.com"
    sender_email: ${SMTP_SENDER_EMAIL}
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:enable: true


  rabbitmq:
    # Use your environment variables
    addresses: ${RABBITMQ_URL}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    # Name of the queue
    queue: "EMAIL"
    exchange: "amq.direct"