
database:
  db_name: ""
  username: ""
  password: ""

spring:
  # On "development" profile, use "update" to create the tables
  jpa:hibernate:ddl-auto: validate

  # Mail service configuration
  mail:
    sender_email: ""
    sender_name: ""
    host: ""
    username: ""
    password: ""
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:enable: true

  security:
    token:
      # Token unique password for sign, generate on https://guidgenerator.com/
      password: ""
      # Time in minutes for the token to be expired after generated
      expiration_minutes: 15
