
project:
  api:
    domainUrl: "http://localhost:8080"

server:
  port: 8080


spring:
  jpa:hibernate:ddl-auto: update

  mail:
    sender_email: "support@oldbot.com.br"
    sender_name: "No Reply OldBot"
    host: smtp.titan.email
    username: support@oldbot.com.br
    password: fWicKmtKuk
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:enable: true

  rabbitmq:
    #host: localhost
    #port: 5672
    addresses: amqps://eqiczbow:sOoJIJb1atphJGKrpuW0Ryfnvoi1m32A@jackal.rmq.cloudamqp.com/eqiczbow
    username: eqiczbow
    password: sOoJIJb1atphJGKrpuW0Ryfnvoi1m32A
    queue: "EMAIL"
    exchange: "amq.direct"
